### ISSUE TITLE
Typo in "REMOVING NODES IN A LINKED LIST"

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/linked-lists-reading#1]
In the last paragraph of the section "REMOVING NODES IN A LINKED LIST", the last line has a typo:

> We'll let you code this procedure in the next exercise. The important thing for now is to notice that the cost of this was relatively cheap. The only thing that can get costly is the number of times we need to call next to access the index we are adding our node to. So the cost of adding or removing elements is big O of the index we are adding to. When adding elements towards the **beginning of the linked list** this will be significantly less than adding elements to the **beginning of a linked list**, which is big O of n.

It should be:

> We'll let you code this procedure in the next exercise. The important thing for now is to notice that the cost of this was relatively cheap. The only thing that can get costly is the number of times we need to call next to access the index we are adding our node to. So the cost of adding or removing elements is big O of the index we are adding to. When adding elements towards the **beginning of the linked list** this will be significantly less than adding elements to the _**end of a linked list**_, which is big O of n.

**Comment by gj** [comment]
Thanks @kjleitz !
